# Regression Analysis
## Statistical Analysis of Waste Management Practices in Sri Lanka

### Project
Statistical Analysis of Waste Management Practices Among
Households and Business Establishments in Sri Lanka

### Analysis
Regression Analysis

### Team Members
1. Member 1
2. Member 2
3. Member 3

# ***1***. ***Introduction***

---
## Purpose of the Analysis
---

Regression analysis is used in this study to examine the relationships between selected waste management factors and a specific waste management outcome.

The collected survey data will be used to develop a regression model using a dependent variable and selected independent variables. The performance of the model will be evaluated using suitable statistical measures, and the required regression assumptions will also be checked to ensure that the results are reliable.

# ***3***. ***Objectives***

#  ***4***. ***Data*** ***Loading***

In [ ]:
# Import required libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
from scipy import stats

print("Libraries imported successfully.")

df = pd.read_excel('New combined data set.xlsx',sheet_name='Cleaned Data')

print("Excel file loaded successfully.")

Libraries imported successfully.
Excel file loaded successfully.

In [ ]:
print("Dataset Shape:")
print(df.shape)

#for check the columns
print("\nColumn Names:")
for i, col in enumerate(df.columns):
    print(i, ":", col)

Dataset Shape:
(301, 51)

Column Names:
0 : Timestamp
1 : Email
2 : Q1. Age
3 : Q2. Province
4 : Q3. District
5 : Q4. Local Authority
6 : Q5. Area Type
7 : Q6. Place Type
8 : Q7. No. of People
9 : Q8. Land Size
10 : Q9. Waste Storage Method
11 : Q10. Bag Size
12 : Q11. Bin Size
13 : Q12a. Food Waste (bags)
14 : Q12b. Garden Waste (bags)
15 : Q12c. Plastic (bags)
16 : Q12d. Paper (bags)
17 : Q12e. Glass (bags)
18 : Q12f. Metal (bags)
19 : Q12g. E-Waste (bags)
20 : Q12h. Textile (bags)
21 : Q12i. Rubber (bags)
22 : Q12j. Coconut (bags)
23 : Q12k. Packaging (bags)
24 : Q12l. Medical (bags)
25 : Q12m. Other (bags)
26 : Q13a. Food Waste (bins)
27 : Q13b. Garden Waste (bins)
28 : Q13c. Plastic (bins)
29 : Q13d. Paper (bins)
30 : Q13e. Glass (bins)
31 : Q13f. Metal (bins)
32 : Q13g. E-Waste (bins)
33 : Q13h. Textile (bins)
34 : Q13i. Rubber (bins)
35 : Q13j. Coconut (bins)
36 : Q13k. Packaging (bins)
37 : Q13l. Medical (bins)
38 : Q13m. Other (bins)
39 : Q14. Separate Recyclables?
40 : Q15. Recycle Waste?
41 : Q16. How Recycle?
42 : Q17. Income from Recyclables?
43 : Q18. Monthly Income (Rs.)
44 : Q19. Distance to Collection Point
45 : Q20. Collection Frequency
46 : Q21. Disposal Method
47 : Q22. Monthly Spend (Rs.)
48 : Q23. Biggest Problem
49 : Q24. Use Mobile App?
50 : Q25. Satisfaction

In [ ]:
#to display 1st five rows
print("\nFirst 5 Rows:")
display(df.head())

First 5 Rows:

,Timestamp,Email,Q1. Age,Q2. Province,Q3. District,Q4. Local Authority,Q5. Area Type,Q6. Place Type,Q7. No. of People,Q8. Land Size,...,Q16. How Recycle?,Q17. Income from Recyclables?,Q18. Monthly Income (Rs.),Q19. Distance to Collection Point,Q20. Collection Frequency,Q21. Disposal Method,Q22. Monthly Spend (Rs.),Q23. Biggest Problem,Q24. Use Mobile App?,Q25. Satisfaction
0,2026-06-23 11:58:15.956000,ransikasachin@gmail.com,50 - 59 years,Western,Colombo (කොළඹ),Maharagama Urban Council,Semi-urban (අර්ධ නාගරික),Household,3 - 4 persons,10–19 perches (250–499 m²),...,Other: __________,No,NaN,More than 2 km,Weekly,Municipal collection service (මහ නගර / ප්‍රාදේ...,No expenditure,Lack of recycling facilities,Yes,Very Satisfied
1,2026-06-23 12:01:51.647000,dulminipabasara0501@gmail.com,70 years and above,Western,Colombo (කොළඹ),Maharagama Urban Council,Urban (නාගරික),Household,1 - 2 persons,10–19 perches (250–499 m²),...,Reuse at home,No,NaN,No collection point available,Twice a week,Municipal collection service (මහ නගර / ප්‍රාදේ...,No expenditure,Other: __________,No,Neutral
2,2026-06-23 12:09:26.388000,ranuraindudunu2004@gmail.com,70 years and above,Western,Colombo (කොළඹ),Maharagama Urban Council,Urban (නාගරික),Household,5 - 6 persons,10–19 perches (250–499 m²),...,Hand over to recycling centers,Yes,"Rs. 5,000 and above",More than 2 km,Weekly,Municipal collection service (මහ නගර / ප්‍රාදේ...,No expenditure,Other: __________,Yes,Very Satisfied
3,2026-06-23 12:16:28.910000,ranuraindudunu2004@gmail.com,40 - 49 years,Western,Colombo (කොළඹ),Maharagama Urban Council,Urban (නාගරික),Annex,3 - 4 persons,Less than 10 perches (<250 m²),...,Other: __________,No,NaN,More than 2 km,Weekly,Municipal collection service (මහ නගර / ප්‍රාදේ...,No expenditure,Lack of recycling facilities,Yes,Satisfied
4,2026-06-23 12:22:06.377000,benurijayodya@gmail.com,30 - 39 years,Western,Colombo (කොළඹ),Maharagama Urban Council,Semi-urban (අර්ධ නාගරික),Household,More than 8 persons,20–39 perches (500–999 m²),...,Other: __________,No,NaN,No collection point available,Weekly,Municipal collection service (මහ නගර / ප්‍රාදේ...,Rs. 500–999,Bad smell/pests,Yes,Neutral

In [ ]:
#to load which type of data stored in each column
print("\nData Types:")
print(df.dtypes)

Data Types:
Timestamp                            object
Email                                object
Q1. Age                              object
Q2. Province                         object
Q3. District                         object
Q4. Local Authority                  object
Q5. Area Type                        object
Q6. Place Type                       object
Q7. No. of People                    object
Q8. Land Size                        object
Q9. Waste Storage Method             object
Q10. Bag Size                        object
Q11. Bin Size                        object
Q12a. Food Waste (bags)              object
Q12b. Garden Waste (bags)            object
Q12c. Plastic (bags)                 object
Q12d. Paper (bags)                   object
Q12e. Glass (bags)                   object
Q12f. Metal (bags)                   object
Q12g. E-Waste (bags)                 object
Q12h. Textile (bags)                 object
Q12i. Rubber (bags)                  object
Q12j. Coconut (bags)                 object
Q12k. Packaging (bags)               object
Q12l. Medical (bags)                 object
Q12m. Other (bags)                   object
Q13a. Food Waste (bins)              object
Q13b. Garden Waste (bins)            object
Q13c. Plastic (bins)                 object
Q13d. Paper (bins)                   object
Q13e. Glass (bins)                   object
Q13f. Metal (bins)                   object
Q13g. E-Waste (bins)                 object
Q13h. Textile (bins)                 object
Q13i. Rubber (bins)                  object
Q13j. Coconut (bins)                 object
Q13k. Packaging (bins)               object
Q13l. Medical (bins)                 object
Q13m. Other (bins)                   object
Q14. Separate Recyclables?           object
Q15. Recycle Waste?                  object
Q16. How Recycle?                    object
Q17. Income from Recyclables?        object
Q18. Monthly Income (Rs.)            object
Q19. Distance to Collection Point    object
Q20. Collection Frequency            object
Q21. Disposal Method                 object
Q22. Monthly Spend (Rs.)             object
Q23. Biggest Problem                 object
Q24. Use Mobile App?                 object
Q25. Satisfaction                    object
dtype: object

In [ ]:
for col in df.columns:
    print("\n", col)
    print(df[col].unique()[:20])

 Timestamp
['2026-06-23 11:58:15.956000' '2026-06-23 12:01:51.647000'
 '2026-06-23 12:09:26.388000' '2026-06-23 12:16:28.910000'
 '2026-06-23 12:22:06.377000' '2026-06-23 13:54:00.917000'
 '2026-06-23 13:58:26.738000' '2026-06-27 07:15:04.802000'
 '2026-06-27 09:54:45.925000' '2026-06-27 10:18:29.868000'
 '2026-06-28 17:01:19.720000' '2026-06-28 21:32:53.008000'
 '2026-06-29 17:28:07.637000' '2026-06-29 18:10:01.302000'
 '2026-06-29 18:10:56.745000' '2026-06-29 18:16:05.502000'
 '2026-06-29 19:08:54.262000' '2026-06-29 19:26:36.723000'
 '2026-06-29 20:12:12.245000' '2026-06-29 21:25:36.543000']

 Email
['ransikasachin@gmail.com' 'dulminipabasara0501@gmail.com'
 'ranuraindudunu2004@gmail.com' 'benurijayodya@gmail.com'
 'chulaniniroshika@gmail.com' 'thathsaraninavodya04@gmail.com'
 'dewmikaveesha438@gmail.com' 'heshanimanushika@gmail.com'
 'skvindya1112@gmail.com' 'hirunisanjanadeshapriya2004@gmail.com'
 'vishmichamodya31@gmail.com' 'swethachamidini@gmail.com'
 'samanthaedirimuni320@gmail.com' 'nishadiwickramaarachchi52@gmail.com'
 'viwandi2003@gmail.com' 'mehansajayasundara@gmail.com'
 'senithya07@gmail.com' 'indikajlis2003@gmail.com'
 'dsk.sandeep.987@gmail.com' 'aribjibbrey@gmail.com']

 Q1. Age
['50 - 59 years' '70 years and above' '40 - 49 years' '30 - 39 years'
 '60 - 69 years' '20 - 29 years' 'Below 20 years']

 Q2. Province
['Western' 'Southern' 'Eastern' 'Sabaragamuwa' 'Central' 'Northern'
 'North Western' 'North Central' 'Uva']

 Q3. District
['Colombo (කොළඹ)' 'Gampaha (ගම්පහ)' 'Galle (ගාල්ල)' 'Kalutara (කළුතර)'
 'Kegalle (කෑගල්ල)' 'Kandy (මහනුවර)' 'Jaffna (යාපනය)' 'Matara (මාතර)'
 'Kurunegala (කුරුණෑගල)' 'Hambantota (හම්බන්තොට)' 'Ratnapura (රත්නපුර)'
 'Anuradhapura (අනුරාධපුරය)' 'Ampara (අම්පාර)' 'Puttalam (පුත්තලම)'
 'Badulla (බදුල්ල)' 'Matale (මාතලේ)']

 Q4. Local Authority
['Maharagama Urban Council' 'Gampaha Municipal Council'
 'Nagoda Pradeshiya Sabha' 'Colombo Municipal Council'
 'Kesbewa Urban Council' 'Horana Urban Council' 'Bentota Pradeshiya Sabha'
 'Mathugama Pradeshiya Sabha' 'Kegalle Municipal Council'
 'Madurawala Pradeshiya Sabha' 'Kalutara Municipal Council'
 'Attanagalla Pradeshiya Sabha' 'Rambukkana Pradeshiya Sabha'
 'Kaduwela Municipal Council' 'Kelaniya Pradeshiya Sabha'
 'Ganga Ihala Korale Pradeshiya Sabha' 'Nallur Pradeshiya Sabha'
 'Sri Jayawardenepura Kotte Municipal Council' 'Matara Municipal Council'
 'Narammala Pradeshiya Sabha']

 Q5. Area Type
['Semi-urban (අර්ධ නාගරික)' 'Urban (නාගරික)' 'Rural (ග්\u200dරාමීය)']

 Q6. Place Type
['Household' 'Annex' 'Restaurant' 'Shop/Retail Business' 'Office']

 Q7. No. of People
['3 - 4 persons' '1 - 2 persons' '5 - 6 persons' 'More than 8 persons'
 '7 - 8 persons']

 Q8. Land Size
['10–19 perches (250–499 m²)' 'Less than 10 perches (<250 m²)'
 '20–39 perches (500–999 m²)' '40–79 perches (1000–1999 m²)'
 '80 perches and above (>2000 m²)']

 Q9. Waste Storage Method
['Waste Bags' 'Both Bags and Bins' 'Waste Bins' 'Other (Specify)'
 'Burning in a garbage dump' 'Pit' 'Garbage pit'
 'We have a separate place within our land For garage managment']

 Q10. Bag Size
['Jumbo Bag' 'Extra Large Bag' 'Medium Bag' 'Small Bag' 'Large Bag' nan]

 Q11. Bin Size
[nan 'Large Bin' 'Small Bin' 'Medium Bin' 'Extra Large Bin' 'Jumbo Bin'
 'Extra Jumbo Bin']

 Q12a. Food Waste (bags)
['1.0' '1/2' '8.0' '5.0' nan '2.0' '0.0' '6.0' '1/2, 1, 2' '7.0' '3.0'
 'More than 10' '4.0' '1, 2' '1/2, 1' '4, 7' '10.0']

 Q12b. Garden Waste (bags)
['1.0' '1/2' nan '2.0' 'More than 10' '3.0' '5.0' '4.0' '0.0' '6.0' '3, 6'
 '9.0' '7.0' '0, 1/2' '10.0' '1, 4']

 Q12c. Plastic (bags)
['1.0' '1/2' nan '3.0' '2.0' '4.0' '6.0' '5.0' '0.0' '0, 1/2' '1, 2'
 '1/2, 1']

 Q12d. Paper (bags)
[nan '1/2' '1.0' '4.0' '2.0' '3.0' '5.0' '0.0' '0, 1/2' '7.0' '1/2, 1']

 Q12e. Glass (bags)
[nan '1/2' '0.0' '2.0' '1.0' '3.0' '0, 1/2' '2, 5']

 Q12f. Metal (bags)
[nan '1/2' '0.0' '1.0' '2.0' '1/2, 4' '0, 1/2' '3.0' '3, 5' '4.0' '0, 1'
 '1/2, 1']

 Q12g. E-Waste (bags)
[nan '1/2' '0.0' '1.0' '2.0' '0, 1/2' '3.0' '2, 5']

 Q12h. Textile (bags)
[nan '1/2' '0.0' '1.0' '2.0' '0, 1/2' '3.0' '1/2, 1' '1/2, 2' '0, 1/2, 1']

 Q12i. Rubber (bags)
[nan '1/2' '0.0' '2.0' '1.0' '0, 1/2' '4.0' '3.0']

 Q12j. Coconut (bags)
[nan '1/2' '1.0' '7.0' '2.0' '0.0' '3.0' '6.0' '1/2, 1' 'More than 10'
 '5.0' '4.0' '1, 2' '10.0' '0, 1/2']

 Q12k. Packaging (bags)
[nan '1/2' '0.0' '2.0' '3.0' '5.0' '4.0' '7.0' '1.0' '0, 1/2' '9, 10'
 '1/2, 1' '10.0' '1, 2']

 Q12l. Medical (bags)
[nan '1/2' '0.0' '2.0' '1.0' '0, 1/2' '4.0' '6.0' '1, 2']

 Q12m. Other (bags)
[nan '1/2' '0.0' '1.0' '1/2, 1' '2.0' '5.0' '7.0' '3.0' '6.0']

 Q13a. Food Waste (bins)
[nan '1.0' '2.0' '1, 2' '1/2' '0.0' '6.0' '3.0' '4.0' '1/2, 1' '10.0'
 '7.0' 'More than 10' '5.0' '8.0']

 Q13b. Garden Waste (bins)
[nan '2.0' '5.0' '1/2' '1.0' '0.0' '6.0' '4.0' '0, 1/2' '1/2, 1'
 'More than 10' '3.0' '4, 5' '9.0' '7.0' '10.0']

 Q13c. Plastic (bins)
[nan '1.0' '1/2' '0.0' '2.0' '3.0' '0, 1/2' '4.0' '5.0' '1/2, 1' '6.0'
 '7.0']

 Q13d. Paper (bins)
[nan '1.0' '0.0' '1/2' '2.0' '4.0' '0, 1/2' '1/2, 1' '3.0' '5.0' '6.0']

 Q13e. Glass (bins)
[nan '1/2' '0.0' '1.0' '2.0' '0, 1/2' '5.0']

 Q13f. Metal (bins)
[nan '1/2' '0.0' '1.0' '0, 1/2' '1, 2' '0, 3' '2.0' '5.0' '1/2, 1']

 Q13g. E-Waste (bins)
[nan '1/2' '0.0' '1.0' '0, 1/2' '2.0' '5.0' '3, 4, 7']

 Q13h. Textile (bins)
[nan '2.0' '0.0' '1.0' '1/2' '0, 1/2' '5.0' '1/2, 1' '3.0']

 Q13i. Rubber (bins)
[nan '1/2' '0.0' '1.0' '0, 1' '0, 1/2' '3.0' '2.0' '5.0']

 Q13j. Coconut (bins)
[nan '5.0' '0.0' '1.0' '2.0' '6.0' '1/2' '3.0' '7.0' '1/2, 1'
 'More than 10' '0, 1/2' '10.0' '9.0' '4.0']

 Q13k. Packaging (bins)
[nan '1/2' '0.0' '1.0' '3.0' '5.0' '2.0' '0, 1/2' '9.0' '6.0' '1/2, 1']

 Q13l. Medical (bins)
[nan '1/2' '0.0' '1.0' '2, 3' '2.0' '0, 1/2' '0, 1' '5.0' '4.0']

 Q13m. Other (bins)
[nan '1/2' '0.0' '1.0' '0, 1/2' '3.0' '5.0' '2.0']

 Q14. Separate Recyclables?
['Yes' 'No']

 Q15. Recycle Waste?
['No' 'Yes']

 Q16. How Recycle?
['Other: __________' 'Reuse at home' 'Hand over to recycling centers' nan
 'Sell to collectors' '-' 'No' 'Buy to lorry' 'Use food waste as bio gas'
 'Do all of them']

 Q17. Income from Recyclables?
['No' 'Yes' nan]

 Q18. Monthly Income (Rs.)
[nan 'Rs. 5,000 and above' 'Less than Rs. 500' 'Rs. 500–999' '-'
 'Rs. 1,000–2,999' 'Rs. 3,000–4,999' 'No' "Don't know" 'Not selling'
 'Rs 100.00']

 Q19. Distance to Collection Point
['More than 2 km' 'No collection point available' '100–499 m' '1–2 km'
 '500–999 m' 'Less than 100 m']

 Q20. Collection Frequency
['Weekly' 'Twice a week' 'Other: __________' 'Monthly' 'Daily'
 'Once every two weeks' 'No' 'Nope' 'Never' 'No collection'
 'Do not collect' 'Never collect' 'Not come to collect' nan
 'no proper collection' 'no proper collecting method' 'Not collecting'
 'Special colleting programs conducted by Pradeshiya Sabha']

 Q21. Disposal Method
['Municipal collection service (මහ නගර / ප්\u200dරාදේශීය සභා සේවාව මගින්)'
 'Municipal collection service (මහ නගර / ප්\u200dරාදේශීය සභා සේවාව මගින්), Private collection service (පෞද්ගලික එකතු කිරීමේ සේවාව මගින්)'
 'Municipal collection service (මහ නගර / ප්\u200dරාදේශීය සභා සේවාව මගින්), Composting (කොම්පෝස්ට් කිරීම)'
 'Composting (කොම්පෝස්ට් කිරීම), Burying (වළ දැමීම)'
 'Burning in an open area (විවෘතව ගිනි තැබීම)'
 'Private collection service (පෞද්ගලික එකතු කිරීමේ සේවාව මගින්), Composting (කොම්පෝස්ට් කිරීම), Burning in an open area (විවෘතව ගිනි තැබීම)'
 'Composting (කොම්පෝස්ට් කිරීම), Burying (වළ දැමීම), Burning in an open area (විවෘතව ගිනි තැබීම)'
 'Municipal collection service (මහ නගර / ප්\u200dරාදේශීය සභා සේවාව මගින්), Burying (වළ දැමීම)'
 'Composting (කොම්පෝස්ට් කිරීම), Burning in an open area (විවෘතව ගිනි තැබීම)'
 'Burying (වළ දැමීම), Burning in an open area (විවෘතව ගිනි තැබීම)'
 'Municipal collection service (මහ නගර / ප්\u200dරාදේශීය සභා සේවාව මගින්), Private collection service (පෞද්ගලික එකතු කිරීමේ සේවාව මගින්), Composting (කොම්පෝස්ට් කිරීම)'
 'Composting (කොම්පෝස්ට් කිරීම)'
 'Private collection service (පෞද්ගලික එකතු කිරීමේ සේවාව මගින්)'
 'Municipal collection service (මහ නගර / ප්\u200dරාදේශීය සභා සේවාව මගින්), Composting (කොම්පෝස්ට් කිරීම), Burying (වළ දැමීම)'
 'Municipal collection service (මහ නගර / ප්\u200dරාදේශීය සභා සේවාව මගින්), Burning in an open area (විවෘතව ගිනි තැබීම)'
 'Private collection service (පෞද්ගලික එකතු කිරීමේ සේවාව මගින්), Burning in an open area (විවෘතව ගිනි තැබීම)'
 'Dumping in open areas (විවෘත ස්ථානවල දැමීම), Burning in an open area (විවෘතව ගිනි තැබීම)'
 'Burying (වළ දැමීම)'
 'Municipal collection service (මහ නගර / ප්\u200dරාදේශීය සභා සේවාව මගින්), Composting (කොම්පෝස්ට් කිරීම), Burning in an open area (විවෘතව ගිනි තැබීම)'
 'Private collection service (පෞද්ගලික එකතු කිරීමේ සේවාව මගින්), Burying (වළ දැමීම), Burning in an open area (විවෘතව ගිනි තැබීම)']

 Q22. Monthly Spend (Rs.)
['No expenditure' 'Rs. 500–999' 'Less than Rs. 500' 'Rs. 1,000–2,999'
 'Rs. 5,000 and above' 'Rs. 3,000–4,999']

 Q23. Biggest Problem
['Lack of recycling facilities' 'Other: __________' 'Bad smell/pests'
 'Irregular waste collection'
 'Limited space for waste storage, Bad smell/pests'
 'Limited space for waste storage'
 'Irregular waste collection, Lack of awareness, Bad smell/pests'
 'Irregular waste collection, Lack of recycling facilities, Bad smell/pests'
 'Irregular waste collection, Lack of recycling facilities'
 'Irregular waste collection, Limited space for waste storage'
 'Lack of recycling facilities, Limited space for waste storage, Bad smell/pests'
 'Irregular waste collection, Limited space for waste storage, Bad smell/pests'
 'Lack of recycling facilities, Bad smell/pests'
 'Irregular waste collection, Lack of recycling facilities, Limited space for waste storage, Bad smell/pests'
 'Irregular waste collection, Lack of recycling facilities, High cost of waste disposal, Limited space for waste storage, Bad smell/pests'
 'High cost of waste disposal, Bad smell/pests'
 'Lack of recycling facilities, Limited space for waste storage' 'Nothing'
 'Irregular waste collection, Lack of recycling facilities, Limited space for waste storage'
 'Irregular waste collection, Lack of recycling facilities, Lack of awareness, High cost of waste disposal, Limited space for waste storage, Bad smell/pests']

 Q24. Use Mobile App?
['Yes' 'No']

 Q25. Satisfaction
['Very Satisfied' 'Neutral' 'Satisfied' 'Very Dissatisfied' 'Dissatisfied']

In [ ]:
#to make a copy of original data
clean_df = df.copy()

print("Original rows:", len(clean_df))

Original rows: 301

#Data Cleaning

In [ ]:
#to remove timestamp and gmail from Cleaned Data sheet
clean_df = clean_df.drop(columns=['Timestamp', 'Email'])

print("Rows after removing columns:", len(clean_df))

Rows after removing columns: 301

In [ ]:
#to clean spaces in text
for col in clean_df.columns:
    if clean_df[col].dtype == 'object':
        clean_df[col] = clean_df[col].apply(
            lambda x: x.strip() if isinstance(x, str) else x
        )

In [ ]:
#to remark Mandatory questions
mandatory_cols = [
    'Q1. Age',
    'Q2. Province',
    'Q3. District',
    'Q4. Local Authority',
    'Q5. Area Type',
    'Q6. Place Type',
    'Q7. No. of People',
    'Q8. Land Size',
    'Q9. Waste Storage Method',
    'Q14. Separate Recyclables?',
    'Q15. Recycle Waste?',
    'Q19. Distance to Collection Point',
    'Q20. Collection Frequency',
    'Q21. Disposal Method',
    'Q22. Monthly Spend (Rs.)',
    'Q23. Biggest Problem',
    'Q24. Use Mobile App?',
    'Q25. Satisfaction'
]

In [ ]:
for col in mandatory_cols:
    clean_df[col] = clean_df[col].replace(r'^\s*$', np.nan, regex=True)

clean_df = clean_df.dropna(subset=mandatory_cols)

print("Rows after mandatory-field cleaning:", len(clean_df))

Rows after mandatory-field cleaning: 300

In [ ]:
error_rows = clean_df[
    clean_df[mandatory_cols].isna().any(axis=1)
]

print("Rows containing errors:")
print(error_rows[mandatory_cols])

print("\nOriginal row numbers:")
print(error_rows.index.tolist())

Rows containing errors:
Empty DataFrame
Columns: [Q1. Age, Q2. Province, Q3. District, Q4. Local Authority, Q5. Area Type, Q6. Place Type, Q7. No. of People, Q8. Land Size, Q9. Waste Storage Method, Q14. Separate Recyclables?, Q15. Recycle Waste?, Q19. Distance to Collection Point, Q20. Collection Frequency, Q21. Disposal Method, Q22. Monthly Spend (Rs.), Q23. Biggest Problem, Q24. Use Mobile App?, Q25. Satisfaction]
Index: []

Original row numbers:
[]

In [ ]:
#q16 contain answers like "No", "-". to normalize it
clean_df['Q16. How Recycle?'] = clean_df['Q16. How Recycle?'].replace(
    ['-', 'No'],
    np.nan
)

In [ ]:
#to Q15 → Q16 validation
q16_invalid = (
    ((clean_df['Q15. Recycle Waste?'] == 'Yes') &
     (clean_df['Q16. How Recycle?'].isna())) |

    ((clean_df['Q15. Recycle Waste?'] == 'No') &
     (clean_df['Q16. How Recycle?'].notna()))
)

print("Invalid Q15/Q16 rows:", q16_invalid.sum())

Invalid Q15/Q16 rows: 35

In [ ]:
#to see what are those rows have to remove in Q15 → Q16 validation
clean_df.loc[q16_invalid, [
    'Q15. Recycle Waste?',
    'Q16. How Recycle?'
]]

    Q15. Recycle Waste?               Q16. How Recycle?
0                    No               Other: __________
3                    No               Other: __________
4                    No               Other: __________
9                    No                   Reuse at home
16                   No              Sell to collectors
21                  Yes                             NaN
32                   No  Hand over to recycling centers
34                  Yes                             NaN
40                   No  Hand over to recycling centers
56                   No              Sell to collectors
59                  Yes                             NaN
83                   No  Hand over to recycling centers
84                   No              Sell to collectors
90                   No              Sell to collectors
92                   No                   Reuse at home
95                   No  Hand over to recycling centers
111                  No                   Reuse at home
112                 Yes                             NaN
113                  No                   Reuse at home
125                  No              Sell to collectors
145                  No              Sell to collectors
160                  No              Sell to collectors
182                  No  Hand over to recycling centers
183                  No                   Reuse at home
184                  No              Sell to collectors
187                  No              Sell to collectors
190                  No  Hand over to recycling centers
193                  No              Sell to collectors
203                  No              Sell to collectors
205                  No              Sell to collectors
212                  No              Sell to collectors
241                  No  Hand over to recycling centers
246                  No              Sell to collectors
250                  No              Sell to collectors
284                  No              Sell to collectors

In [ ]:
#q18 can contain answers like "no", "-". To normalize it.
clean_df['Q18. Monthly Income (Rs.)'] = clean_df[
    'Q18. Monthly Income (Rs.)'
].replace(
    ['-', 'No', 'Not selling'],
    np.nan
)

In [ ]:
#to Q17 → Q18 validation
q18_invalid = (
    ((clean_df['Q17. Income from Recyclables?'] == 'Yes') &
     (clean_df['Q18. Monthly Income (Rs.)'].isna())) |

    ((clean_df['Q17. Income from Recyclables?'] == 'No') &
     (clean_df['Q18. Monthly Income (Rs.)'].notna()))
)

print("Invalid Q17/Q18 rows:", q18_invalid.sum())

Invalid Q17/Q18 rows: 27

In [ ]:
#to see what are those rows have to remove in Q17 → Q18 validation

clean_df.loc[q18_invalid, [
    'Q17. Income from Recyclables?',
    'Q18. Monthly Income (Rs.)'
]]

    Q17. Income from Recyclables? Q18. Monthly Income (Rs.)
5                              No       Rs. 5,000 and above
11                             No         Less than Rs. 500
60                            Yes                       NaN
63                             No               Rs. 500–999
66                             No       Rs. 5,000 and above
68                             No         Less than Rs. 500
92                             No         Less than Rs. 500
101                            No         Less than Rs. 500
138                           Yes                       NaN
151                            No       Rs. 5,000 and above
171                           Yes                       NaN
182                            No       Rs. 5,000 and above
183                            No                Don't know
203                            No               Rs. 500–999
210                            No         Less than Rs. 500
215                            No         Less than Rs. 500
218                            No         Less than Rs. 500
219                            No         Less than Rs. 500
230                            No         Less than Rs. 500
231                            No         Less than Rs. 500
233                            No         Less than Rs. 500
246                            No         Less than Rs. 500
248                            No         Less than Rs. 500
263                            No               Rs. 500–999
275                            No       Rs. 5,000 and above
290                            No         Less than Rs. 500
291                            No         Less than Rs. 500

In [ ]:
#to Q19 → Q21 validation
q21_invalid = (
    (clean_df['Q19. Distance to Collection Point'] ==
     'No collection point available')
    &
    (
        clean_df['Q21. Disposal Method'].str.contains(
            'Municipal collection service|Private collection service',
            case=False,
            na=False
        )
    )
)

print("Invalid Q19/Q21 rows:", q21_invalid.sum())

Invalid Q19/Q21 rows: 38

In [ ]:
#to see what are those rows have to remove in Q19 → Q21 validation

clean_df.loc[q21_invalid, [
    'Q19. Distance to Collection Point',
    'Q21. Disposal Method'
]]

,Q19. Distance to Collection Point,Q21. Disposal Method
1,No collection point available,Municipal collection service (මහ නගර / ප්‍රාදේ...
4,No collection point available,Municipal collection service (මහ නගර / ප්‍රාදේ...
5,No collection point available,Municipal collection service (මහ නගර / ප්‍රාදේ...
6,No collection point available,Municipal collection service (මහ නගර / ප්‍රාදේ...
7,No collection point available,Municipal collection service (මහ නගර / ප්‍රාදේ...
12,No collection point available,Private collection service (පෞද්ගලික එකතු කිරී...
14,No collection point available,Municipal collection service (මහ නගර / ප්‍රාදේ...
15,No collection point available,Municipal collection service (මහ නගර / ප්‍රාදේ...
21,No collection point available,Municipal collection service (මහ නගර / ප්‍රාදේ...
24,No collection point available,Municipal collection service (මහ නගර / ප්‍රාදේ...
47,No collection point available,Municipal collection service (මහ නගර / ප්‍රාදේ...
54,No collection point available,Municipal collection service (මහ නගර / ප්‍රාදේ...
60,No collection point available,Municipal collection service (මහ නගර / ප්‍රාදේ...
62,No collection point available,Municipal collection service (මහ නගර / ප්‍රාදේ...
67,No collection point available,Municipal collection service (මහ නගර / ප්‍රාදේ...
70,No collection point available,Municipal collection service (මහ නගර / ප්‍රාදේ...
72,No collection point available,Private collection service (පෞද්ගලික එකතු කිරී...
75,No collection point available,Municipal collection service (මහ නගර / ප්‍රාදේ...
80,No collection point available,Municipal collection service (මහ නගර / ප්‍රාදේ...
92,No collection point available,Private collection service (පෞද්ගලික එකතු කිරී...
115,No collection point available,Municipal collection service (මහ නගර / ප්‍රාදේ...
119,No collection point available,Municipal collection service (මහ නගර / ප්‍රාදේ...
127,No collection point available,Municipal collection service (මහ නගර / ප්‍රාදේ...
136,No collection point available,Municipal collection service (මහ නගර / ප්‍රාදේ...
147,No collection point available,Municipal collection service (මහ නගර / ප්‍රාදේ...
153,No collection point available,Municipal collection service (මහ නගර / ප්‍රාදේ...
165,No collection point available,Private collection service (පෞද්ගලික එකතු කිරී...
180,No collection point available,Municipal collection service (මහ නගර / ප්‍රාදේ...
194,No collection point available,Municipal collection service (මහ නගර / ප්‍රාදේ...
201,No collection point available,Municipal collection service (මහ නගර / ප්‍රාදේ...
223,No collection point available,Municipal collection service (මහ නගර / ප්‍රාදේ...
231,No collection point available,Municipal collection service (මහ නගර / ප්‍රාදේ...
273,No collection point available,Municipal collection service (මහ නගර / ප්‍රාදේ...
275,No collection point available,Municipal collection service (මහ නගර / ප්‍රාදේ...
276,No collection point available,Municipal collection service (මහ නගර / ප්‍රාදේ...
277,No collection point available,Municipal collection service (මහ නගර / ප්‍රාදේ...
284,No collection point available,Municipal collection service (මහ නගර / ප්‍රාදේ...
296,No collection point available,Municipal collection service (මහ නගර / ප්‍රාදේ...

In [ ]:
print(
    clean_df['Q9. Waste Storage Method']
    .value_counts(dropna=False)
)

Q9. Waste Storage Method
Both Bags and Bins                                               135
Waste Bins                                                       105
Waste Bags                                                        49
Other (Specify)                                                    7
Burning in a garbage dump                                          1
Pit                                                                1
Garbage pit                                                        1
We have a separate place within our land For garage managment      1
Name: count, dtype: int64

In [ ]:
print("========== CLEANING CHECK ==========")

print("\nTotal rows:")
print(len(clean_df))

print("\nQ15 → Q16 invalid:")
print(q16_invalid.sum())

print("\nQ17 → Q18 invalid:")
print(q18_invalid.sum())

print("\nQ19 → Q21 invalid:")
print(q21_invalid.sum())

print("\nQ9 Waste Storage Methods:")
print(clean_df['Q9. Waste Storage Method'].value_counts(dropna=False))

========== CLEANING CHECK ==========

Total rows:
300

Q15 → Q16 invalid:
35

Q17 → Q18 invalid:
27

Q19 → Q21 invalid:
38

Q9 Waste Storage Methods:
Q9. Waste Storage Method
Both Bags and Bins                                               135
Waste Bins                                                       105
Waste Bags                                                        49
Other (Specify)                                                    7
Burning in a garbage dump                                          1
Pit                                                                1
Garbage pit                                                        1
We have a separate place within our land For garage managment      1
Name: count, dtype: int64

In [ ]:
#to inspect individual invalid records
invalid_data = clean_df.loc[
    invalid_rows,
    [
        'Q15. Recycle Waste?',
        'Q16. How Recycle?',
        'Q17. Income from Recyclables?',
        'Q18. Monthly Income (Rs.)',
        'Q19. Distance to Collection Point',
        'Q21. Disposal Method'
    ]
]

display(invalid_data)

,Q15. Recycle Waste?,Q16. How Recycle?,Q17. Income from Recyclables?,Q18. Monthly Income (Rs.),Q19. Distance to Collection Point,Q21. Disposal Method
0,No,Other: __________,No,NaN,More than 2 km,Municipal collection service (මහ නගර / ප්‍රාදේ...
1,Yes,Reuse at home,No,NaN,No collection point available,Municipal collection service (මහ නගර / ප්‍රාදේ...
3,No,Other: __________,No,NaN,More than 2 km,Municipal collection service (මහ නගර / ප්‍රාදේ...
4,No,Other: __________,No,NaN,No collection point available,Municipal collection service (මහ නගර / ප්‍රාදේ...
5,Yes,Reuse at home,No,"Rs. 5,000 and above",No collection point available,Municipal collection service (මහ නගර / ප්‍රාදේ...
...,...,...,...,...,...,...
277,Yes,Hand over to recycling centers,No,NaN,No collection point available,Municipal collection service (මහ නගර / ප්‍රාදේ...
284,No,Sell to collectors,Yes,Rs. 500–999,No collection point available,Municipal collection service (මහ නගර / ප්‍රාදේ...
290,Yes,Hand over to recycling centers,No,Less than Rs. 500,1–2 km,Municipal collection service (මහ නගර / ප්‍රාදේ...
291,No,NaN,No,Less than Rs. 500,More than 2 km,Municipal collection service (මහ නගර / ප්‍රාදේ...
296,No,NaN,No,NaN,No collection point available,Municipal collection service (මහ නගර / ප්‍රාදේ...

In [ ]:
q16_invalid = (
    ((clean_df['Q15. Recycle Waste?'] == 'Yes') &
     (clean_df['Q16. How Recycle?'].isna()))
    |
    ((clean_df['Q15. Recycle Waste?'] == 'No') &
     (clean_df['Q16. How Recycle?'].notna()))
)

print("Q15 → Q16 invalid after cleaning:", q16_invalid.sum())

Q15 → Q16 invalid after cleaning: 35

In [ ]:
q18_invalid = (
    ((clean_df['Q17. Income from Recyclables?'] == 'Yes') &
     (clean_df['Q18. Monthly Income (Rs.)'].isna()))
    |
    ((clean_df['Q17. Income from Recyclables?'] == 'No') &
     (clean_df['Q18. Monthly Income (Rs.)'].notna()))
)

print("Q17 → Q18 invalid after cleaning:", q18_invalid.sum())

Q17 → Q18 invalid after cleaning: 27

In [ ]:
q21_invalid = (
    (clean_df['Q19. Distance to Collection Point'] ==
     'No collection point available')
    &
    (
        clean_df['Q21. Disposal Method'].str.contains(
            'Municipal collection service|Private collection service',
            case=False,
            na=False
        )
    )
)

print("Q19 → Q21 invalid:", q21_invalid.sum())

Q19 → Q21 invalid: 38

In [ ]:
q9_other = clean_df[
    ~clean_df['Q9. Waste Storage Method'].isin(
        ['Waste Bags', 'Waste Bins', 'Both Bags and Bins']
    )
]

display(
    q9_other[
        [
            'Q9. Waste Storage Method',
            'Q10. Bag Size',
            'Q11. Bin Size',
            'Q12a. Food Waste (bags)',
            'Q12b. Garden Waste (bags)',
            'Q13a. Food Waste (bins)',
            'Q13b. Garden Waste (bins)'
        ]
    ]
)

,Q9. Waste Storage Method,Q10. Bag Size,Q11. Bin Size,Q12a. Food Waste (bags),Q12b. Garden Waste (bags),Q13a. Food Waste (bins),Q13b. Garden Waste (bins)
12,Other (Specify),Medium Bag,Medium Bin,2.0,3.0,1.0,1.0
13,Other (Specify),Medium Bag,Medium Bin,1/2,2.0,1.0,2.0
18,Other (Specify),NaN,NaN,NaN,NaN,NaN,NaN
28,Other (Specify),Medium Bag,Small Bin,6.0,6.0,6.0,6.0
31,Other (Specify),Large Bag,NaN,1/2,1.0,1/2,1.0
33,Other (Specify),Small Bag,Small Bin,1/2,1.0,1.0,1.0
35,Other (Specify),Large Bag,NaN,2.0,4.0,2.0,4.0
72,Burning in a garbage dump,NaN,Extra Jumbo Bin,1/2,2.0,"1/2, 1",2.0
132,Pit,Medium Bag,Medium Bin,2.0,2.0,2.0,2.0
159,Garbage pit,NaN,NaN,1.0,3.0,NaN,NaN
160,We have a separate place within our land For g...,NaN,Medium Bin,1/2,2.0,1/2,2.0

In [ ]:
bag_cols = [
    'Q10. Bag Size',
    'Q12a. Food Waste (bags)',
    'Q12b. Garden Waste (bags)',
    'Q12c. Plastic (bags)',
    'Q12d. Paper (bags)',
    'Q12e. Glass (bags)',
    'Q12f. Metal (bags)',
    'Q12g. E-Waste (bags)',
    'Q12h. Textile (bags)',
    'Q12i. Rubber (bags)',
    'Q12j. Coconut (bags)',
    'Q12k. Packaging (bags)',
    'Q12l. Medical (bags)',
    'Q12m. Other (bags)'
]

bin_cols = [
    'Q11. Bin Size',
    'Q13a. Food Waste (bins)',
    'Q13b. Garden Waste (bins)',
    'Q13c. Plastic (bins)',
    'Q13d. Paper (bins)',
    'Q13e. Glass (bins)',
    'Q13f. Metal (bins)',
    'Q13g. E-Waste (bins)',
    'Q13h. Textile (bins)',
    'Q13i. Rubber (bins)',
    'Q13j. Coconut (bins)',
    'Q13k. Packaging (bins)',
    'Q13l. Medical (bins)',
    'Q13m. Other (bins)'
]

In [ ]:
bags_only_invalid = (
    (clean_df['Q9. Waste Storage Method'] == 'Waste Bags')
    &
    (clean_df[bin_cols].notna().any(axis=1))
)

print("Waste Bags → invalid bin information:",
      bags_only_invalid.sum())

Waste Bags → invalid bin information: 31

In [ ]:
bins_only_invalid = (
    (clean_df['Q9. Waste Storage Method'] == 'Waste Bins')
    &
    (clean_df[bag_cols].notna().any(axis=1))
)

print("Waste Bins → invalid bag information:",
      bins_only_invalid.sum())

Waste Bins → invalid bag information: 85

In [ ]:
bags_size_missing = (
    (clean_df['Q9. Waste Storage Method'] == 'Waste Bags')
    &
    (clean_df['Q10. Bag Size'].isna())
)

print("Waste Bags → missing bag size:",
      bags_size_missing.sum())

Waste Bags → missing bag size: 0

In [ ]:
bins_size_missing = (
    (clean_df['Q9. Waste Storage Method'] == 'Waste Bins')
    &
    (clean_df['Q11. Bin Size'].isna())
)

print("Waste Bins → missing bin size:",
      bins_size_missing.sum())

Waste Bins → missing bin size: 1

In [ ]:
both_bag_bin_size_invalid = (
    (clean_df['Q9. Waste Storage Method'] == 'Both Bags and Bins')
    &
    (
        clean_df['Q10. Bag Size'].isna()
        |
        clean_df['Q11. Bin Size'].isna()
    )
)

print(
    "Both Bags and Bins → missing bag/bin size:",
    both_bag_bin_size_invalid.sum()
)

Both Bags and Bins → missing bag/bin size: 2

In [ ]:
#waste bag respondents with both bag and bin info
display(
    clean_df.loc[
        bags_only_invalid,
        [
            'Q9. Waste Storage Method',
            'Q10. Bag Size',
            'Q11. Bin Size',
            'Q12a. Food Waste (bags)',
            'Q12b. Garden Waste (bags)',
            'Q13a. Food Waste (bins)',
            'Q13b. Garden Waste (bins)'
        ]
    ]
)

,Q9. Waste Storage Method,Q10. Bag Size,Q11. Bin Size,Q12a. Food Waste (bags),Q12b. Garden Waste (bags),Q13a. Food Waste (bins),Q13b. Garden Waste (bins)
25,Waste Bags,Medium Bag,Large Bin,2.0,2.0,1.0,1.0
42,Waste Bags,Large Bag,Large Bin,1/2,1/2,1.0,1.0
54,Waste Bags,Small Bag,Small Bin,2.0,0.0,0.0,0.0
101,Waste Bags,Medium Bag,Extra Large Bin,1.0,1.0,0.0,0.0
102,Waste Bags,Medium Bag,Small Bin,1.0,2.0,1.0,2.0
106,Waste Bags,Large Bag,Large Bin,1/2,NaN,1/2,NaN
128,Waste Bags,Extra Large Bag,Extra Large Bin,1/2,1.0,1.0,0.0
136,Waste Bags,Medium Bag,Small Bin,2.0,0.0,4.0,0.0
143,Waste Bags,Medium Bag,Medium Bin,1.0,1.0,NaN,NaN
162,Waste Bags,Medium Bag,Medium Bin,1/2,NaN,NaN,NaN
172,Waste Bags,Large Bag,Large Bin,1.0,1/2,1/2,1/2
173,Waste Bags,Medium Bag,Medium Bin,1.0,1/2,0.0,0.0
178,Waste Bags,Large Bag,Small Bin,1.0,0.0,1.0,0.0
179,Waste Bags,Small Bag,Small Bin,1.0,1.0,2.0,1.0
182,Waste Bags,Large Bag,Medium Bin,1.0,1.0,1.0,1/2
201,Waste Bags,Large Bag,Medium Bin,1.0,0.0,0.0,1/2
207,Waste Bags,Small Bag,Small Bin,1/2,1.0,1.0,2.0
210,Waste Bags,Large Bag,Large Bin,1.0,1/2,2.0,1.0
216,Waste Bags,Small Bag,Small Bin,5.0,2.0,2.0,1.0
217,Waste Bags,Medium Bag,Medium Bin,1.0,1/2,1.0,1/2
223,Waste Bags,Medium Bag,Medium Bin,1.0,1.0,1.0,NaN
229,Waste Bags,Large Bag,Medium Bin,1/2,0.0,1/2,0.0
232,Waste Bags,Medium Bag,Medium Bin,2.0,1/2,1.0,1/2
246,Waste Bags,Medium Bag,Medium Bin,2.0,1.0,2.0,1.0
247,Waste Bags,Large Bag,Small Bin,1/2,1.0,0.0,0.0
249,Waste Bags,Medium Bag,Medium Bin,2.0,4.0,3.0,6.0
269,Waste Bags,Medium Bag,Medium Bin,2.0,2.0,2.0,1.0
271,Waste Bags,Large Bag,Jumbo Bin,4.0,7.0,2.0,10.0
284,Waste Bags,Extra Large Bag,Medium Bin,0.0,1/2,NaN,NaN
289,Waste Bags,Large Bag,Large Bin,1.0,1/2,1.0,1.0
298,Waste Bags,Medium Bag,Small Bin,1.0,1/2,1.0,1/2

In [ ]:
#waste bin respondents with bag info
display(
    clean_df.loc[
        bins_only_invalid,
        [
            'Q9. Waste Storage Method',
            'Q10. Bag Size',
            'Q11. Bin Size',
            'Q12a. Food Waste (bags)',
            'Q12b. Garden Waste (bags)',
            'Q13a. Food Waste (bins)',
            'Q13b. Garden Waste (bins)'
        ]
    ]
)

,Q9. Waste Storage Method,Q10. Bag Size,Q11. Bin Size,Q12a. Food Waste (bags),Q12b. Garden Waste (bags),Q13a. Food Waste (bins),Q13b. Garden Waste (bins)
10,Waste Bins,Medium Bag,Medium Bin,NaN,NaN,1.0,1/2
19,Waste Bins,Large Bag,NaN,1.0,5.0,NaN,NaN
20,Waste Bins,Medium Bag,Medium Bin,1.0,4.0,NaN,NaN
36,Waste Bins,Medium Bag,Medium Bin,2.0,NaN,1.0,NaN
38,Waste Bins,NaN,Extra Large Bin,2.0,0.0,1.0,1.0
...,...,...,...,...,...,...,...
273,Waste Bins,Large Bag,Medium Bin,1/2,1.0,1/2,1.0
277,Waste Bins,Small Bag,Medium Bin,1/2,1.0,1/2,1.0
279,Waste Bins,Medium Bag,Medium Bin,2.0,4.0,3.0,6.0
283,Waste Bins,Small Bag,Small Bin,2.0,1.0,1.0,1.0
288,Waste Bins,NaN,Small Bin,2.0,NaN,2.0,0.0

In [ ]:
#bin respondents with missing bin info
display(
    clean_df.loc[
        bins_size_missing,
        [
            'Q9. Waste Storage Method',
            'Q10. Bag Size',
            'Q11. Bin Size'
        ]
    ]
)

   Q9. Waste Storage Method Q10. Bag Size Q11. Bin Size
19               Waste Bins     Large Bag           NaN

In [ ]:
#both bag and bin respondents with missing info
display(
    clean_df.loc[
        both_bag_bin_size_invalid,
        [
            'Q9. Waste Storage Method',
            'Q10. Bag Size',
            'Q11. Bin Size'
        ]
    ]
)

   Q9. Waste Storage Method Q10. Bag Size Q11. Bin Size
44       Both Bags and Bins           NaN    Medium Bin
57       Both Bags and Bins     Large Bag           NaN

In [ ]:
# Clean Q9-related inconsistent entries

# 1. If respondent selected Waste Bags,
# remove all bin-related information
waste_bags = clean_df['Q9. Waste Storage Method'] == 'Waste Bags'

clean_df.loc[waste_bags, bin_cols] = np.nan


# 2. If respondent selected Waste Bins,
# remove all bag-related information
waste_bins = clean_df['Q9. Waste Storage Method'] == 'Waste Bins'

clean_df.loc[waste_bins, bag_cols] = np.nan


print("Q9-related cleaning completed.")

Q9-related cleaning completed.

In [ ]:
# Check Waste Bags respondents
bags_check = (
    (clean_df['Q9. Waste Storage Method'] == 'Waste Bags') &
    (clean_df[bin_cols].notna().any(axis=1))
)

print("Waste Bags with bin information:", bags_check.sum())


# Check Waste Bins respondents
bins_check = (
    (clean_df['Q9. Waste Storage Method'] == 'Waste Bins') &
    (clean_df[bag_cols].notna().any(axis=1))
)

print("Waste Bins with bag information:", bins_check.sum())

Waste Bags with bin information: 0
Waste Bins with bag information: 0

In [ ]:
# Recalculate Q16 validation
q16_invalid = (
    ((clean_df['Q15. Recycle Waste?'] == 'Yes') &
     (clean_df['Q16. How Recycle?'].isna())) |
    ((clean_df['Q15. Recycle Waste?'] == 'No') &
     (clean_df['Q16. How Recycle?'].notna()))
)


# Recalculate Q18 validation
q18_invalid = (
    ((clean_df['Q17. Income from Recyclables?'] == 'Yes') &
     (clean_df['Q18. Monthly Income (Rs.)'].isna())) |
    ((clean_df['Q17. Income from Recyclables?'] == 'No') &
     (clean_df['Q18. Monthly Income (Rs.)'].notna()))
)


# Recalculate Q19 → Q21 validation
q21_invalid = (
    (clean_df['Q19. Distance to Collection Point'] ==
     'No collection point available')
    &
    (
        clean_df['Q21. Disposal Method'].str.contains(
            'Municipal collection service|Private collection service',
            case=False,
            na=False
        )
    )
)


# Combine all invalid rows
invalid_rows = q16_invalid | q18_invalid | q21_invalid


print("Q15 → Q16 invalid:", q16_invalid.sum())
print("Q17 → Q18 invalid:", q18_invalid.sum())
print("Q19 → Q21 invalid:", q21_invalid.sum())
print("Unique invalid rows:", invalid_rows.sum())

Q15 → Q16 invalid: 35
Q17 → Q18 invalid: 27
Q19 → Q21 invalid: 38
Unique invalid rows: 87

In [ ]:
#rows with invalid details
invalid_data = clean_df.loc[
    invalid_rows,
    [
        'Q15. Recycle Waste?',
        'Q16. How Recycle?',
        'Q17. Income from Recyclables?',
        'Q18. Monthly Income (Rs.)',
        'Q19. Distance to Collection Point',
        'Q21. Disposal Method'
    ]
]

display(invalid_data)

,Q15. Recycle Waste?,Q16. How Recycle?,Q17. Income from Recyclables?,Q18. Monthly Income (Rs.),Q19. Distance to Collection Point,Q21. Disposal Method
0,No,Other: __________,No,NaN,More than 2 km,Municipal collection service (මහ නගර / ප්‍රාදේ...
1,Yes,Reuse at home,No,NaN,No collection point available,Municipal collection service (මහ නගර / ප්‍රාදේ...
3,No,Other: __________,No,NaN,More than 2 km,Municipal collection service (මහ නගර / ප්‍රාදේ...
4,No,Other: __________,No,NaN,No collection point available,Municipal collection service (මහ නගර / ප්‍රාදේ...
5,Yes,Reuse at home,No,"Rs. 5,000 and above",No collection point available,Municipal collection service (මහ නගර / ප්‍රාදේ...
...,...,...,...,...,...,...
277,Yes,Hand over to recycling centers,No,NaN,No collection point available,Municipal collection service (මහ නගර / ප්‍රාදේ...
284,No,Sell to collectors,Yes,Rs. 500–999,No collection point available,Municipal collection service (මහ නගර / ප්‍රාදේ...
290,Yes,Hand over to recycling centers,No,Less than Rs. 500,1–2 km,Municipal collection service (මහ නගර / ප්‍රාදේ...
291,No,NaN,No,Less than Rs. 500,More than 2 km,Municipal collection service (මහ නගර / ප්‍රාදේ...
296,No,NaN,No,NaN,No collection point available,Municipal collection service (මහ නගර / ප්‍රාදේ...

In [ ]:
print("Q15→Q16 AND Q17→Q18:",
      (q16_invalid & q18_invalid).sum())

print("Q15→Q16 AND Q19→Q21:",
      (q16_invalid & q21_invalid).sum())

print("Q17→Q18 AND Q19→Q21:",
      (q18_invalid & q21_invalid).sum())

print("All three:",
      (q16_invalid & q18_invalid & q21_invalid).sum())

Q15→Q16 AND Q17→Q18: 5
Q15→Q16 AND Q19→Q21: 4
Q17→Q18 AND Q19→Q21: 5
All three: 1

In [ ]:
q16_invalid = (
    ((clean_df['Q15. Recycle Waste?'] == 'Yes') &
     (clean_df['Q16. How Recycle?'].isna())) |
    ((clean_df['Q15. Recycle Waste?'] == 'No') &
     (clean_df['Q16. How Recycle?'].notna()))
)

q18_invalid = (
    ((clean_df['Q17. Income from Recyclables?'] == 'Yes') &
     (clean_df['Q18. Monthly Income (Rs.)'].isna())) |
    ((clean_df['Q17. Income from Recyclables?'] == 'No') &
     (clean_df['Q18. Monthly Income (Rs.)'].notna()))
)

q21_invalid = (
    (clean_df['Q19. Distance to Collection Point'] ==
     'No collection point available')
    &
    (
        clean_df['Q21. Disposal Method'].str.contains(
            'Municipal collection service|Private collection service',
            case=False,
            na=False
        )
    )
)

invalid_rows = q16_invalid | q18_invalid | q21_invalid

print("Q15 → Q16 invalid:", q16_invalid.sum())
print("Q17 → Q18 invalid:", q18_invalid.sum())
print("Q19 → Q21 invalid:", q21_invalid.sum())
print("Unique invalid rows:", invalid_rows.sum())

Q15 → Q16 invalid: 35
Q17 → Q18 invalid: 27
Q19 → Q21 invalid: 38
Unique invalid rows: 87

In [ ]:
print("Current number of rows:", len(clean_df))

Current number of rows: 300

In [ ]:
# Save invalid responses first
invalid_data = clean_df.loc[invalid_rows].copy()

# Remove invalid responses
clean_df = clean_df.loc[~invalid_rows].copy()

# Reset index
clean_df = clean_df.reset_index(drop=True)

print("Final cleaned rows:", len(clean_df))

Final cleaned rows: 213

In [ ]:
# Check the number of responses in each district
district_counts = clean_df['Q3. District'].value_counts()

print(district_counts)

Q3. District
Colombo (කොළඹ)               61
Kalutara (කළුතර)             40
Galle (ගාල්ල)                29
Gampaha (ගම්පහ)              28
Kurunegala (කුරුණෑගල)        14
Matara (මාතර)                13
Ratnapura (රත්නපුර)           7
Hambantota (හම්බන්තොට)        5
Kegalle (කෑගල්ල)              4
Anuradhapura (අනුරාධපුරය)     3
Kandy (මහනුවර)                3
Badulla (බදුල්ල)              2
Puttalam (පුත්තලම)            2
Jaffna (යාපනය)                1
Ampara (අම්පාර)               1
Name: count, dtype: int64

In [ ]:
selected_districts = [
    'Colombo (කොළඹ)',
    'Kalutara (කළුතර)',
    'Galle (ගාල්ල)',
    'Gampaha (ගම්පහ)',
    'Kurunegala (කුරුණෑගල)',
    'Matara (මාතර)'
]

clean_df = clean_df[
    clean_df['Q3. District'].isin(selected_districts)
].copy()

clean_df = clean_df.reset_index(drop=True)

print("Final number of responses:", len(clean_df))
print("\nFinal district counts:")
print(clean_df['Q3. District'].value_counts())

Final number of responses: 185

Final district counts:
Q3. District
Colombo (කොළඹ)           61
Kalutara (කළුතර)         40
Galle (ගාල්ල)            29
Gampaha (ගම්පහ)          28
Kurunegala (කුරුණෑගල)    14
Matara (මාතර)            13
Name: count, dtype: int64

In [ ]:
# Export final cleaned dataset to Excel

output_file = 'Final_Cleaned_Waste_Survey_185.xlsx'

clean_df.to_excel(
    output_file,
    index=False
)

print("Excel file created successfully!")
print("File name:", output_file)
print("Number of responses:", len(clean_df))

Excel file created successfully!
File name: Final_Cleaned_Waste_Survey_185.xlsx
Number of responses: 185

In [ ]:
from google.colab import files

files.download('Final_Cleaned_Waste_Survey_185.xlsx')

In [ ]:
print("Rows:", len(clean_df))
print("Columns:", len(clean_df.columns))

print("\nDistrict counts:")
print(clean_df['Q3. District'].value_counts())

Rows: 185
Columns: 49

District counts:
Q3. District
Colombo (කොළඹ)           61
Kalutara (කළුතර)         40
Galle (ගාල්ල)            29
Gampaha (ගම්පහ)          28
Kurunegala (කුරුණෑගල)    14
Matara (මාතර)            13
Name: count, dtype: int64